### ISSUE TITLE
플러그인 에러리포트 - Todo 리스트

### ISSUE THREAD

**Issue by HmHmmHm** [if-Team/Personal#1]
<h1> 이 페이지는 뭔가요? 페이지 안내!

이 페이지는 제가 개발한 플러그인에 추가로
개발 할 내용 공개 및 플러그인의 에러보고를 받는 페이지 입니다!

제가 개발한 플러그인에 에러가 있다면 여기에
댓글로 해당 에러 내용을 알려주세요 ! (최대한 자세하게!)

#에러 보고 양식
1. Pocketmine 버전: (예 1.4버전 DEV 900)
2. 에러 발생 상황: (예: 언제 어디서 누가 무엇을 어떻게 했더니 에러발생-)
3. 에러의 주 내용: (예:  -한 문제가 있으며 -한 에러가 발생하기도 함)
4. 크래시덤프 전송여부: (hmkuak@naver.com 으로 보낸후 Y표시!)

*에러 리포트 전에 다른 플러그인의 문제가 아닌지 확인해주세요.
*플러그인을 모두 빼 보고 해당 플러그인만 동작시켜 확인해주세요.
*이미 아래에 보고되서 수정 중인 내용인지 확인해주세요.

 <h1> TODO 리스트 (1월 2일 수정)

심플에리어 (*개발 중 또는 Todo 내역)
 - [x] 리눅스 환경에서 protect파일이 잘못된 위치에 저장되는 에러잡기
 - [x] /sa make 로 만든 구역에서 /sellhome 시 반응이 없고 에러 발생하는 에러잡기
 - [x] pocketmine.yml에서 불러오지않은 맵이있을시 발생하는 에러잡기
 - [x] /homelist 로 구매가능한 영역 리스트 조회가능하게 하기
 - [ ] 번호로 땅을 구매가능하게 하기
 - [ ] 중복되는 영역개념 허용(유저의 땅이 겹칠 때는 땅을 추가로 확장시키고
    OP의 지역보호가 겹칠 때는 가장 작은 지역보호의 규칙을 우선해서 적용)
 - [x] 지역보호에 PlayerInteractEvent 캐치시켜서 캔슬처리 넣기(표지판 제외)
 - [x] 미구현 기능 환영말/초대/ 등 기능 모두 구현처리
 - [x] 지역보호가 70개가 넘어갈때 에러가 있다는 에러보고 맞는지 확인하기
 - [ ] ↑위에러들 모두 해결하고 심플에리어 1.0 알파 릴리즈 시키기
 - [ ] PvP를 종류별로 나누고 원하는 종류의 PvP만 허용시키는 옵션 개발

나이더스커널 (*개발 중 또는 Todo 내역)
 - [x] pocketmine.yml에서 불러오지않은 맵이있을시 발생하는 에러잡기

이코노미 엔티티 (*개발 중 또는 Todo 내역)
 - [x] PM #916 에서 서버시작시 발생하는 엔티티에러 수정
 - [x] 스켈레톤-몹등에게서 아이템을 중복으로 얻던 에러 수정
 - [x] NPC->주민으로 한글 명령어 수정 적용
 - [x] ↑ 위에러 모두 수정 완료시 이코노미엔티티 3.2 릴리즈
 - [ ] 스폰알을 통한 엔티티 스폰 기능 추가
 - [ ] 유저가 자기 땅에 몹스폰을 해놓으면
    몬스터가 나이가 먹고 그 나이만큼 돈을 보상받게 함

창조경제 플러그인 (*개발 중 또는 Todo 내역)
 - [x] 미리설정 되있는 아이템가격시세 기능
 - [x] 표지판매매-명령어매매 동시지원
 - [x] /상점목록 기능 추가적으로 개발
 - [ ] 상점 구축시 쇼케이스(아이템케이스) 자동 생성기능 포함 시키기
 - [ ] 이름표나 채팅에 붙는 칭호를 상점에서 살 수 있게하기

그룹 플러그인 (미출시) (*개발 중 또는 Todo 내역)
 - [ ] 그룹을 만들어서 다 같이 협동해서 할 수 있게 끔 하게하기
 - [ ] 그룹 관리기능 [PVP 칭호 경제공유 채팅색 그룹채팅]

블러드슈가 플러그인 (미출시) (*개발 중 또는 Todo 내역)
 - [x] 서버에 타격감을 주는 효과들을 내장시키기
 - [x] 피해자를 가해자가 보고있는 방향으로 밀어버리기
 - [x] 공격이 있을 시 폭발하는 효과음을 발생시키기
 - [x] 공격이 있을 시 피해자의 화면을 위 아래로 흔들기
 - [ ] 위 사항 모두 개발 시 블러드슈가 1.0 릴리즈

오토메틱 도어 (*개발 중 또는 Todo 내역)
 - [ ] 문을 설치할때 암호를 설정하는 기능 추가하기

PMMP 갑옷 데미지 해결 플러그인 (*개발 중 또는 Todo 내역)
 - [ ] 헝거게임 플러그인에서 짠 코드를 빼내서 PHAR 화하기

PSYCHO-PASS 프로젝트 (*개발 중 또는 Todo 내역)
 - [ ] 비속어 사전필터 각 플러그인 별 연동시켜놓기
 - [ ] 한 서브넷에서 여러명이 접속해 채팅도배를 시도할 때 자동으로 감지 후 밴 시키는 루틴 작성
 - [ ] 감시관 집행관 플러그인 완성 시키기
 - [ ] 감시관 또는 집행관 주변에 범죄계수가 기준치 이상인 유저가 있을때
   자동으로 리설엘리미네이터 모드로 변경되게 하기

컬러풀 플러그인 (*개발 중 또는 Todo 내역)
 - [ ] 색상표 색상이 제대로 출력되지않는 에러잡기

스노하레 (*개발 중 또는 Todo 내역)
 - [ ] 눈이 쌓이지 않을 블럭을 명령어로 추가하고 삭제하며 리스트를 확인 가능한 기능 추가

게임모드 킥 플러그인 (*개발 중 또는 Todo 내역)
 - [x] 일부 환경에서 정상작동 되지않는 문제가 있음 확인해야함.
 - [ ] setCancelled 가 정상적으로 먹히지않은 코딩에러 수정

버스트 모드 플러그인 (*개발 중 또는 Todo 내역)
 - [ ] 좀 더 빠르고 안정적으로 연사되게 하기
 - [ ] 버스트모드로 나간 활은 주울 수 없게 이벤트 짜기

헝거게임 플러그인 (*개발 중 또는 Todo 내역)
 - [x] 전적 저장 등에 오류가 있다는 일부 환경 보고
 - [x] 전적 표시 방법 좀 더 깔끔하게 정리
 - [x] 유저를 살해 시 전적이 더블로 오르는 에러잡기

솔져게임 플러그인 (*개발 중 또는 Todo 내역)
 - [ ] 유저를 살해 시 전적이 더블로 오르는 에러잡기

튜토리얼 플러그인 (*개발 중 또는 Todo 내역)
 - 서버에 처음 접속시나 /튜토리얼 이용시 서버장이 미리 설정해놓은 튜토리얼 안내메시지와 각 서버장이 완수목표로 해놓은 튜토리얼 해결 미션 등을 해결해야 다음 튜툐리얼로 넘어가게 하는 플러그인 개발.

(※주의- 개발자를 독촉하거나 하진 말아주세요 (´･ω･`)..
한 플러그인 당 PHP코드가 700줄에서 많게는 1200줄이 됩니다.
개발자가 여가시간을 틈틈히 내서 개발하는것이니 양해부탁드려요)

**Comment by dianoGon** [comment]
환영합니다 관리자님
/welcome 로 메세지수정가능
이거 계속떠요....채팅에도배가되뇨 걸을때마다...이거알림메세지없앤거따로 만들어주세요 그리고 지역보호 /sa delete 로안지워져요

**Comment by wsj7178** [comment]
/sa delete 명령어가 씹히네요..

/sa delete 하면 한번더 입력하거나 /sa cancel 입력하라고 뜨는데 거기서 /sa delete 입력하면 아무일도 안일어나고
그다음부터 /sa delete 명령어를 입력해도 아무 명령어도 안뜹니다.

**Comment by HmHmmHm** [comment]
@dianoGon OP의 지역보호 영역 알림은 아예 표시되지않게끔 수정되었습니다만,
영역보호는 3~4 블럭 단위로 여러개 걸으라고 제작한게 결코 아닙니다..
영역보호는 최대한 관리하기 쉽게 한 섹션별로 나눠서 관리하세요

**Comment by HmHmmHm** [comment]
@wsj7178 어떠한 크래시덤프가 떴을텐데
확인 못하셨나요? 그리고 심플에리어 몇버전인지도 적지않으셨네요

**Comment by wsj7178** [comment]
크래시덤프는 안뜨고 심플에리어는 최신버전이에요

**Comment by dianoGon** [comment]
크게해서 두군데를했거든요 그런데 워프를탄곳에도착하면 걸을때마다 환영합니다관리자님 이건 안뜨더라도 /welcome 메세지수정가능 이 알림도좀없애주세요....

**Comment by dianoGon** [comment]
[서버](/welcome 으로 환영메세지 설정가능)
이게 계속떠요..

**Comment by dianoGon** [comment]
그냥 화이트월드하고 수정해도 안돼요 계속떠요

**Comment by HmHmmHm** [comment]
@wsj7178  @dianoGon 심플에리어 0.10 버전 업로드됬습니다. 해당내용 수정했어요

**Comment by GJ77** [comment]
1. Pocketmine 버전: 1.4버전 #930
2. 에러 발생 상황: 서버구동후 SMTP ERROR: QUIT command failed: <br> 밑라인에 발생
3. 에러의 주 내용: [WARNING] RuntimeException: "stream_socket_enable_crypto(): this stream does not support SSL/crypto" (E_WARNING) in "/plugins/src_emailAuth/src/emailAuth/SMTP" at line 274
4. 크래시덤프 전송여부: x

**Comment by HmHmmHm** [comment]
@GJ77 이메일오스는 아직 미완성이기에
서버에서 아직은 사용할 수 없습니다! +모바일에선 되지않을 수 있음

**Comment by GJ77** [comment]
네이버서버를 이용해서 보내려 하거든요..

**Comment by wsj7178** [comment]
1.pocketmine 버전 1.4.1 Dev 945
2. 에러 발생 상황 : itemconsume 플러그인 1.2버전 인데 블럭을 캘시 인벤토리에 블럭이 들어오고 아이템이 드랍됨.
3. 에러의 주 내용 : 2번 과 같음
4. 크래시덤프 전송여부 : x

**Comment by HmHmmHm** [comment]
@wsj7178 아이템컨슘 1.2버전 맞나요?
그리고 어떤 블럭을 캐셨는지도 알려주세요~

**Comment by HmHmmHm** [comment]
@GJ77 메일서버로 전송은 당연히 가능합니다만
아직 인증부가 개발이 덜된 상태에요~

**Comment by wsj7178** [comment]
다시한번 확인해봐도 1.2버전 맞아요
그리고 모든 블럭에서 해당 에러가 발생합니다.

**Comment by HmHmmHm** [comment]
@wsj7178 지금 테스팅이 불가능해서
새벽중에라도 한번 확인해서 수정할게요~

**Comment by ns827** [comment]
메일 폭탄이 10개씩이나... ㄷ

Unwatch 시켜야할듯

**Comment by dianoGon** [comment]
보호를하면 정해진유저만쓸수잇게못하나요

**Comment by miro5879** [comment]
나이더스커널에 문의사항있습니다.

먼저 Timeout을 줘서 Warp를 하고 이동한 후에 유저가 나갔다가 재접속하면 Timeout이 풀리는 것 같습니다.

두번째로 돈이 없어서 이동을 못하는 상황에서도 timeout이 작동합니다. 작동할때 한번더 포탈을 타면 이동이 취소되어버리고 취소된 상태에서 돈을 가지고 이동을 하면 timeout이 작동하질 않습니다.

그리고 추가로 Timeout에서 몇초전에는 '몇초뒤에 이전위치로 복귀됩니다.' 라는 안내메세지가 추가되었으면 좋겠습니다.

좋은 플러그인 많이 만들어주셔서 감사합니다.

**Comment by HmHmmHm** [comment]
@miro5879 에러리포트 감사합니다. 확인 후 수정예정입니다
@dianoGon 퍼미션 조정으로 해결하시기 바랍니다

+ 심플에리어 중복지역 코드 롤백 후 (또는 완성 후)
원하는 지역에만 인벤세이브 기능 키고끄기 기능 추가 예정

**Comment by milk0417** [comment]
흠님이 참 수고가 많으시네여 ㅠㅅㅠ

**Comment by ns827** [comment]
@milk0417 Github issues를 이용한 버그 리포트라는게 꽤 좋긴 한듯

**Comment by miro5879** [comment]
1. Pocketmine 버전: 1.4 #950
2. 에러 발생 상황: 심플에리어 기본 땅 크기관련, 이코노미겜블 확률
3. 에러의 주 내용: 
심플에리어 기본 땅크기를 10과 9로 설정해봤는데 11칸으로 설정되네요.
8로 설정하면 9칸 설정되는 것 같습니다.
확인해주시면 감사하겠습니다~
4. 크래시덤프 전송여부: N

**Comment by HmHmmHm** [comment]
@miro5879 확인했습니다
@ebebebeb 확인했습니다
- 심플에리어 기본 땅크기가 반올림되는 로직에러 수정 예정
- 심플에리어 울타리 부술 시 DB에러 수정 예정
- 이코노미 겜블 로또 확률 로직에러 수정 예정

**Comment by ebebebeb** [comment]
/yap 을 치면 생긴땅 에 들어가면 이 지역을 /buyhome하는지 뜨는데 거기서 /buyhome을 치면 이미 주인이 있다고 떠용

**Comment by wsj7178** [comment]
1. Pocketmine 버전 : 1.4.1 dev-950
2. 에러발생상황 openvpnlock에서 vpn을 사용하지 않는 일반 와이파이도 차단하는 문제발견.
3. 위와 같음
4. N

**Comment by HmHmmHm** [comment]
@wsj7178 아래 상황을 체크해주세요
1. 정말 일반 와이파이가 맞는지 확인
(본인 네트워크가 차단된다면 VPN을 키고있지 않은지 확인)
2. 해당아이피가 OpenVPNLock이 차단하는지 확인
(RakLib Blocking 이 걸리지 않는 지 확인하세요)
3. 1~2의 사항이 틀림이 없다면 차단되는
해당아이피와 OpenVPNLock의 데이터 파일을 보내주세요

**Comment by ebebebeb** [comment]
1. Pocketmine 버전/ 1.4.1 dev-945
2.에러발생상황/ 표지판명령이 서버를 끄고 다시 키면 표지판 명령이 안됩니다.(저장o)
3.위와 같음
4.n

**Comment by HmHmmHm** [comment]
@ebebebeb 에러리포트 감사합니다,
해당에러 수정본 카페에 업로드했어요~

**Comment by iuzincrsg8820** [comment]
포켓마인 한글화 플러그인 에러 나요

http://cafe.naver.com/minecraftpe/2125396

Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to correctly release the reference on free' in [no active file] on line 0

Call Stack:
    0.0000     343392   1. {main}() C:\Users\Administrator\Desktop\PocketMine-MP\PocketMine-MP.phar:0
    0.0156     346408   2. require_once('phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Administrator\Desktop\PocketMine-MP\PocketMine-MP.phar:1

RuntimeException: yaml_parse(): end of stream reached without finding document 0 in phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 137

Call Stack:
    0.0000     343392   1. {main}() C:\Users\Administrator\Desktop\PocketMine-MP\PocketMine-MP.phar:0
    0.0156     346408   2. require_once('phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Administrator\Desktop\PocketMine-MP\PocketMine-MP.phar:1
    0.1716     455896   3. pocketmine\Server->__construct() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:442
    1.6692   12495328   4. pocketmine\Server->enablePlugins() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1694
    1.7628   12879544   5. pocketmine\Server->enablePlugin() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1764
    1.7628   12879544   6. pocketmine\plugin\PluginManager->enablePlugin() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1778
    1.7628   12879560   7. pocketmine\plugin\PharPluginLoader->enablePlugin() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:559
    1.7628   12879624   8. pocketmine\plugin\PluginBase->setEnabled() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PharPluginLoader.php:123
    1.7628   12879648   9. SignCommand\SignCommand->onEnable() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginBase.php:86
    1.7628   12881672  10. pocketmine\plugin\PluginBase->reloadConfig() phar://C:/Users/Administrator/Desktop/PocketMine-MP/plugins/SignCommand_v1.0-alpha.phar/src/SignCommand/SignCommand.php:17
    1.7628   12881928  11. pocketmine\utils\Config->__construct() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginBase.php:259
    1.7628   12882072  12. pocketmine\utils\Config->load() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php:75
    1.7628   12882136  13. yaml_parse() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php:137
    1.7628   12883264  14. ExceptionHandler::handler() phar://C:/Users/Administrator/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php:137

**Comment by HmHmmHm** [comment]
@iuzincrsg8820 개인환경문제입니다
제 PC에선 950 정상적으로 한글화 변환됬습니다.
![12421312](https://cloud.githubusercontent.com/assets/8337568/5851468/178dfe88-a24b-11e4-9bd3-74f96eab2297.png)

**Comment by cloud9350** [comment]
1. PocketMine-MP 버젼 : PocketMine-Soft 1.4 #916
2. 에러 발생상황 : 누군가가 sethome 한 후 그 구역안에 블럭을 놓으면 오류발생
3. 에러의 주내용
[CRITICAL] Could not pass event pocketmine\event\block\BlockPlaceEvent to SimpleArea v0.10-alpha: Undefined offset: 1 on SimpleArea\SimpleArea
[NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/SimpleArea.phar/src/SimpleArea/SimpleArea_Database" at line 231
4. N (크러시 덤프가 없음)

그냥 PocketMine-Soft 새로 설치해서 SimpleArea 넣어도 발생.
Windows 에서는 오류가 나지 않지만, Linux 환경에서는 오류 발생.

**Comment by HmHmmHm** [comment]
@cloud9350 멀티월드 사용중 아니신가요?
pocketmine.yml에서 로드 하세요

**Comment by cloud9350** [comment]
@HmHmmHm 해결 - Universe 플러그인 삭제

**Comment by ebebebeb** [comment]
1.pocketmine/#945
2.@
/sa allow 61 (화로코드)를 허용시켰습니다.(지역이 보호된 상태) 근데 유저들이 화로가 안부셔지거나 안열린다고 합니다.(저장o) (음 이런걸 오류라고해야되낭..)
3.위와같음
4.n

**Comment by ruddn0101** [comment]
1.pockmine/#945
2.에러상황:땅구매 명령어 칠시 에러뿜음
3.에러 주내용:sethome이쳐질시 에러를 내뿜음 섭다운은안댐 섭지장없음 로그 저장
4.크래시 덤프 전송여부:Y

**Comment by cloud9350** [comment]
@ruddn0101 Universe 플러그인을 삭제해보세요.

**Comment by dbsgh8496** [comment]
PocketMine-MP 버전 1.4.1dev-945
EconomyEntities 3.4 

스켈레톤 소환후 죽이면 에러 발생

Fatal error: Cannot use object of type pocketmine\utils\Config as array in phar://C:/Users/Administrator/Desktop/MapleStory Server/PocketMine-MP/plugins/EconomyEntities_v3.4-alpha.phar/src/hm/EconomyEntities/EconomyEntities.php on line 251
17:43:51 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
17:43:51 [EMERGENCY] Please submit the "C:\Users\Administrator\Desktop\MapleStory Server\PocketMine-MP\CrashDump_Sat_Jan_24-17.43.51-KST_2015.log" file to the Bug Reporting page. Give as much info as you can.
17:43:54 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/792170 or use the ID #792170.

**Comment by dbsgh8496** [comment]
PocketMine-MP 버전 1.4.1dev-945
 EconomyEntities 3.5 

/엔티티 활성화 하고
엔티티 소환후 죽이면 에러 발생 

Fatal error: Call to a member function getId() on integer in phar://C:/Users/Administrator/Desktop/MapleStory/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/inventory/BaseInventory.php on line 240
22:58:14 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
22:58:14 [EMERGENCY] Please submit the "C:\Users\Administrator\Desktop\MapleStory\PocketMine-MP\CrashDump_Sat_Jan_24-22.58.14-KST_2015.log" file to the Bug Reporting page. Give as much info as you can.
22:58:16 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/798696 or use the ID #798696.

**Comment by dbsgh8496** [comment]
엔티티 소 . 닭 . 주민 . 스켈레톤 등등 소환시

터치하거나 죽이면 에러 발생 합니다.

PocketMine-MP 버전 1.4.1dev-945
EconomyEntities 3.5

Fatal error: Call to a member function getId() on integer in phar://C:/Users/Administrator/Desktop/MapleStory/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/inventory/BaseInventory.php on line 240
 22:58:14 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
 22:58:14 [EMERGENCY] Please submit the "C:\Users\Administrator\Desktop\MapleStory\PocketMine-MP\CrashDump_Sat_Jan_24-22.58.14-KST_2015.log" file to the Bug Reporting page. Give as much info as you can.
 22:58:16 [EMERGENCY] The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/798696 or use the ID #798696.

Windows 만 이런가요??
아니면 구버전 사용해야되나요??

**Comment by miro5879** [comment]
Pocketmine 버전:1.4 #950
에러 발생 상황: 버그
에러의 주 내용:
ChestGuard플러그인에서

다른사람의 창고 옆에 자신의 창고를 설치하여 큰창고로 만들면 다른사람의 창고템이 훔쳐지는 것 같습니다.

크래시덤프 전송여부: N

**Comment by cloud9350** [comment]
1. PocketMine-MP 버젼 : PocketMine-Soft 1.4 #916
2. 에러 발생상황 : 주민을 제외한 모든 엔티티를 스폰시켜서 터치하였을때
3. 
11:31:47 [CRITICAL] Could not execute task Callback#hm\EconomyEntities\EconomyEntities::Respawn: Undefined index: BotSpawnList
11:31:47 [NOTICE] ArrayOutOfBoundsException: "Undefined index: BotSpawnList" (E_NOTICE) in "/EconomyEntities_v3.5-alpha.phar/src/hm/EconomyEntities/EconomyEntities" at line 428
11:31:55 [CRITICAL] Could not execute task Callback#hm\EconomyEntities\EconomyEntities::Respawn: Undefined index: BotSpawnList
11:31:55 [NOTICE] ArrayOutOfBoundsException: "Undefined index: BotSpawnList" (E_NOTICE) in "/EconomyEntities_v3.5-alpha.phar/src/hm/EconomyEntities/EconomyEntities" at line 428

발생후 서버 강제종료됨.
4. CrashDump 없이 바로 Killed 떠버림.

환경 : CentOS 7 64Bit, PHP 직접 컴파일, 32GB RAM, 3.4GHz 8core

**Comment by cloud9350** [comment]
이 플러그인 그냥 에러나요! 다른건 모르겠네요! 알아서 고쳐주세요!
.. 는 진짜고요 ㅇㅅㅇ...

1. PocketMine-MP 버젼 : PocketMine-MP 1.4.1dev-954
2. 그냥 나무 심으면 랜덤하게 오류남(...)
3.
17:05:33 [CRITICAL] Could not pass event pocketmine\event\block\BlockUpdateEvent to GreenBelt v1.0-alpha: Class GreenBelt\SmallTree not found on GreenBelt\GreenBelt
17:05:33 [CRITICAL] ClassNotFoundException: "Class GreenBelt\SmallTree not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 122
17:05:33 [CRITICAL] Could not pass event pocketmine\event\block\BlockUpdateEvent to GreenBelt v1.0-alpha: Class GreenBelt\SmallTree not found on GreenBelt\GreenBelt
17:05:33 [CRITICAL] ClassNotFoundException: "Class GreenBelt\SmallTree not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 122
4. 단순히 저 오류만 발생하고 나무가 안자람

**Comment by milgip123** [comment]
PSYCHO-PASS 프로젝트 의 개선점 

/i 1
을할시 1번유져가 아이피밴을당합니다
하지만 이명령어를치기전에 누군가가 나가면 번호는 바뀌게됩니다 그래서 이유없이 밴이되는 경우가 많았죠

개인적으로 PSYCHO-PASS프로젝트 마음에듭니다!
하지만 위사항을 개선하면 더좋을것같습니다

예를들어
/l 을하면 60초동안 번호 교채 ×  나간사람포함

그럼 수고하십쇼

**Comment by milgip123** [comment]
워프플러그인 개선점

1. 돈지불하고 야생월드로 워프했으나 나갔다들어오면 스폰월드에 있습니다.. 

2./warp [야생월드] 하면 돈을내지않고도 워프를할수있습니다(확인은안해봄.)

**Comment by ebebebeb** [comment]
시간이 없어서 양식대로는 못쓸것같습니다.  ㅡ.ㅡ 심플에리어에서 보호된 구역에서 /sa delete 를 두번 하면 오류가 생깁니다.

**Comment by nardem** [comment]
1. Pocketmine 버전: 1.4버전 DEV 233
2. 에러 발생 상황: babel 한글화를 콘솔로사용
3. 에러의 주 내용: 콘솔에 엉청길게 뜸그리고 translate가안생김
4. 크래시덤프 전송여부: N

**Comment by HmHmmHm** [comment]
위에 에러 전부 확인 완료.
에러로 해당되는 사항없음(...)

**Comment by JKH8574** [comment]
1. PocketMine-MP 1.4.1dev954
2. /sethome -> /sellhome 치고 /buyhome 했는데 땅이 안사진다.
3.
[Server] 21:40:51 [CRITICAL] Unhandled exception executing command 'buyhome' in buyhome: Undefined offset: 0
[Server] 21:40:51 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/SimpleArea_v0_11-alpha.phar/src/SimpleArea/SimpleArea" at line 600
4. 없음

**Comment by ChalkPE** [comment]
DEPRECATED : 이 저장소는 더 이상 사용되지 않습니다
